name: Run autotests


on:
  workflow_dispatch:
    inputs:
      deplyoment_target:
        description: select tests to run
        required: true
        type: choice
        default: all
        options:
          - all
jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Tests
    steps: 
      - name: Copy source code
        uses: actions/checkout@v4
      - name: Set up python environment
        uses: actions/setup-python@v5
        with: 
          python-version: "3.12.4"
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest --alluredir=allure-results
  genetare-report:
    runs-on: ubuntu-latest
    needs: run-tests
    name: Generate report
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '17'
      - run: sudo wget https://github.com/allure-framework/allure2/releases/download/2.23.2/allure-2.23.2.tgz && sudo tar -zxvf allure-2.23.2.tgz -C /opt/ && sudo ln -s /opt/allure-2.23.2/bin/allure /usr/bin/allure
      - run: allure generate -c allure-results -o _site
